config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user

  validates :subject, format: {:with => /\A[A-Za-z0-9',\-\séàèçùîï]*\z/}
  validates :content, format: {:with => /\A[A-Za-z0-9',\-\séàèçùîï?.!+*()=&:]*\z/}
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :destroy, :report]
  before_action :logged_in_user, only: [:new, :respond, :index, :show, :create, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where(:receiver_id => current_user.id)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/:id/new
  def new
    @message = Message.new
  end

  # GET /messages/:id/respond
  def respond
    @message = Message.new
    render :new
  end


  def report
    MessageMailer.report(@message).deliver_now
    redirect_to products_path
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @message.sender_name = current_user.profile.first_name + ' ' + current_user.profile.last_name
    @message.sender_nickname = current_user.profile.nickname
    receiver = User.find(params[:id])
    @message.receiver_id = receiver.id
    @message.receiver_name = receiver.profile.first_name + ' ' + receiver.profile.last_name
    @message.receiver_nickname = receiver.profile.nickname
    @message.user_id = current_user.id
    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

  def logged_in_user
    unless logged_in?
      flash[:notice] = 'Please log in.'
      redirect_to login_path
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :sender_id, :sender_name, :sender_nickname, :receiver_id,
                                      :receiver_name, :receiver_nickname, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender name</th>
      <th>Receiver name</th>
      <th>Date</th>
      <th>Subject</th>
      <th>Content</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><% if current_user.admin? %><%= link_to message.sender_name, user_path(message.sender_id) %>
            <% else %><%= link_to message.sender_nickname, user_path(message.sender_id) %><% end %></td>
        <td><% if current_user.admin? %><%= link_to message.receiver_name, user_path(message.receiver_id) %>
              <% else %><%= link_to message.receiver_nickname, user_path(message.receiver_id) %><% end %></td>
        <td><%= message.created_at %></td>
        <td><%= message.subject %></td>
        <td><%= message.content %></td>
        <td><%= button_to 'Show message', message_path(message), method: :get %>
            <% if User.where(:id => message.sender_id) != [] %>
              <%= button_to 'respond message', message_respond_path(message.sender_id), method: :get %>
            <% else %>  
              <p>Sender does not exist anymore.</p>
            <% end %>
            <%= button_to 'Remove message', message_destroy_path(message), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for @message, :url => message_create_path(params[:id]) do |f| %>
    <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

          <ul>
            <% @message.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :subject %><br>
      <%= f.text_field :subject %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, cols:80, rows:10 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back to your messages', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Sender:</strong>
  <% if current_user.admin? %><%= link_to @message.sender_name, user_path(@message.sender_id) %>
  <% else %><%= link_to @message.sender_nickname, user_path(@message.sender_id) %><% end %>
</p>

<p>
  <strong>Receiver:</strong>
  <% if current_user.admin? %><%= link_to @message.receiver_name, user_path(@message.receiver_id) %>
  <% else %><%= link_to @message.receiver_nickname, user_path(@message.receiver_id) %><% end %>
</p>

<p>
  <strong>Date:</strong>
  <%= @message.created_at %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Report message to webmaster', message_report_path(@message), class: "btn btn-large btn-primary" %>
<%= button_to 'Back to your messages', messages_path, method: :get, class: "btn btn-large btn-primary" %>
<% if User.where(:id => @message.sender_id) != [] %>
<%= button_to 'respond message', message_respond_path(@message.sender_id), method: :get, class: "btn btn-large btn-primary" %>
<% else %>
<p>Sender does not exist anymore.</p>
<% end %>
<%= button_to 'Remove message', message_destroy_path(@message), method: :delete, class: "btn btn-large btn-primary" %>