config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  # common input search for all page
  def common_search
    product = Product.find_by(:title => params[:title])
    if product != nil
      redirect_to product_path(product)
    else
      flash[:notice] = 'No result'
      redirect_to products_path
    end  
  end

  # way to search page
  def search
    respond_to do |format|
      format.html { render :search }
    end
  end

  # search engine
  def google
    @products = Product.all
    if params[:title] != ''
      @products = @products.select {|product| product if (product.title.include? params[:title])}
    end
    if params[:category] != ''
      category = Category.find_by(:name => params[:category])
      categories = get_categories(category)
      category_ids = categories.split('_')
      @products = @products.select {|product| product if (category_ids.include? product.category_id.to_s)}
    end
    if params[:maximum_bid] != ''
      @products = @products.select {|product| product if (product.bids.length == 0 && product.start_price <=
          params[:maximum_bid].to_i || product.bids.length != 0 && product.bid_in_progress(product).to_i <= params[:maximum_bid].to_i)}
    end
    if params[:minimum_bid] != ''
      @products = @products.select {|product| product if (product.bids.length == 0 && product.start_price >=
          params[:minimum_bid].to_i || product.bids.length != 0 && product.bid_in_progress(product).to_i >= params[:minimum_bid].to_i)}
    end
    if params[:max_date_bidding_end] != ''
      @products = @products.select {|product| product if (product.date_bidding_end <= params[:max_date_bidding_end])}
    end
    if params[:min_date_bidding_end] != ''
      @products = @products.select {|product| product if (product.date_bidding_end >= params[:min_date_bidding_end])}
    end
    if params[:max_date_bidding_start] != ''
      @products = @products.select {|product| product if (product.date_bidding_start <= params[:max_date_bidding_start])}
    end
    if params[:min_date_bidding_start] != ''
      @products = @products.select {|product| product if (product.date_bidding_start >= params[:min_date_bidding_start])}
    end
    if params[:min_immediate_price] != ''
      @products = @products.select {|product| product if (product.immediate_price != nil)}
      @products = @products.select {|product| product if product.immediate_price <= params[:min_immediate_price].to_i}
    end
    if params[:max_immediate_price] != ''
      @products = @products.select {|product| product if (product.immediate_price != nil)}
      @products = @products.select {|product| product if product.immediate_price >= params[:max_immediate_price].to_i}
    end
    if @products == []
      flash[:notice] = 'No result'
    else  
      flash[:notice] =  @products.length.to_s + ' results.'
      @products
    end  
  end

  private

  def get_categories(category)
    categories = (category.id).to_s
    category.subcategories.each do |sub|
      categories += '_'
      categories += (get_categories(sub)).to_s
    end
    categories
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/google.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'New search ?', search_path, method: :get %>

<h1>Listing search</h1>

<table id="search">
  <thead>
  <tr>
    <th>Owner</th>
    <th>Picture</th>
    <th>Immediate price</th>
    <th>Date bidding end
    <th>Date bidding start</th>
    <th>Bidding time left</th>
    <th>Start price</th>
    <th>Minimum bid</th>
    <th>Bid</th>
    <th>Title</th>
    <th>Category</th>
    <th>Description</th>
    <th>Views</th>
    <th>Rate</th>
    <% if logged_in? && current_user.admin? %>
        <th>Status</th>
    <% end %>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
      <% if product.status == 'In selling' || (logged_in? && current_user.admin?) %>
          <tr>
            <td><% if logged_in? && current_user.admin? %><%= link_to product.user.profile.first_name + ' ' +
                                                          product.user.profile.last_name, user_path(product.user_id) %>
                  <% else %><%= link_to product.user.profile.nickname, user_path(product.user_id) %>
              <% end %></td>
            <td><% if product.image.url != nil %><div class="img"><%= image_tag product.image.url %></div>
              <% else %>empty
              <% end %></td>
            <td><% if product.immediate_price != nil %><%= product.immediate_price %> €
              <% else %>empty<% end %></td>
            <td><%= product.date_bidding_end %></td>
            <td><% if product.status == 'In selling' %><%= product.date_bidding_start %>
                <% else %>Product not confirm<% end %></td>
            <td><% if product.date_bidding_end - Time.now > 0 && product.status == 'In selling' %>
                  <%= distance_of_time_in_words(product.date_bidding_end - Time.now) %>
              <% else %>
                  Bid is over
              <% end %></td>
            <td><%= product.start_price %> €</td>
            <td><%= product.minimum_bid %> €</td>
            <td><% if product.bids.length == 0 %>
                  No bid
              <% else %>
                  <%= product.bid_in_progress(product) %> €
              <% end %>
              <% if logged_in? && Time.now < product.date_bidding_end && product.status == 'In selling' &&
                  product.user_id != current_user.id && (product.bids.length ==0 || product.bid_winner(product).user_id != current_user.id) %>
                  <%= button_to "Add minimum bid", new_minimum_bid_path(product.id, current_user.id) %>
                  <%= form_tag new_custom_bid_path(product.id, current_user.id) do %>
                      <%= number_field_tag :bid %>
                      <%= submit_tag 'Add custom bid', class: "btn btn-large btn-primary" %>
                  <% end %>
                  <%= form_tag new_max_automatic_bid_path(product.id, current_user.id) do %>
                      <%= number_field_tag :max_automatic_bid %>
                      <%= submit_tag 'Add max automatic bid', class: "btn btn-large btn-primary" %>
                  <% end %>
              <% end %>
              <% if logged_in? && product.status == 'sold' && product.bid_winner(product).user_id == current_user.id %>
                  <%= button_to 'buy ' + product.title, buy_path(product, product.bid_id(product)) %>
              <% end %>
              <% if product.bids.length != 0 && product.bid_winner(product).user_id == current_user.id &&
                  product.status =='In selling' %>This is your bid
              <% elsif product.bids.length != 0 && product.user_id == current_user.id %>This is your product
              <% end %></td>
            <td><%= product.title %></td>
            <td><% if product.category_id != nil%>
                  <%= link_to product.category.name, category_path(product.category.id) %>
              <% else %>
                  empty
              <% end %></td>
            <td><%= product.description %></td>
            <td><%= product.views %></td>
            <td><% if product.evaluations.length != 0 %>
                  <% note = 0 %>
                  <% product.evaluations.each do |evaluation| %>
                      <% note += evaluation.rate %>
                  <% end %>
                  <%= note / product.evaluations.length %> / 5
              <% else %>
                  empty
              <% end %></td>
            <% if logged_in? && current_user.admin? %>
                <td><%= product.status %>
                  <% if product.status == 'wait_confirmation' %>
                      <%= button_to 'Confirm', confirm_path(product.id) %><%= button_to 'Not confirm', not_confirm_path(product.id) %>
                  <% end %>
                </td>
            <% end %>
            <td><%= button_to 'Show product', product, method: :get, class: "btn btn-large btn-primary" %>
              <% if logged_in? && (current_user.id != product.user_id || current_user.admin?) %>
                  <%= button_to 'Add evaluation', new_eval_path('Product', product.id), class: "btn btn-large btn-primary" %>
                  <%= button_to 'Ask question' , message_new_path(product.user_id), method: :get, class: "btn btn-large btn-primary" %>
              <% end %>
              <% if logged_in? && ((current_user.id == product.user_id && product.bids.length == 0 &&
                  product.date_bidding_end > Time.now ) || current_user.admin?) %>
                  <%= button_to 'Edit', edit_product_path(product), method: :get, class: "btn btn-large btn-primary" %>
                  <%= button_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %><% end %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
  <p>Average bidding amount:<strong><% @products = @products.select {|product| product if (product.status == 'In selling')}
                                       average = 0
                                       length = @products.length
                                       if length != 0
                                         @products.each do |product|
                                           average += product.bid_in_progress(product).to_i
                                         end
                                         @average = average / length
                                       end %>
                                    <% if @average != nil %><%= @average %><% else %>Empty<% end %></strong></p>
</table>

<br>


<%= button_to 'New search ?', search_path, method: :get, class: "btn btn-large btn-primary" %>

app/views/search/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Page</h1>

<%= form_tag google_path, method: :get do  %>
    <div class="field">
      <%= label_tag :title %><br>
      <%= autocomplete_field_tag :title, '', products_path %>
    </div>
    <div class="field">
      <%= label_tag :category %><br>
      <%= autocomplete_field_tag :category, '', categories_path %>
    </div>
    <div class="field">
      <%= label_tag :maximum_bid %><br>
      <%= number_field_tag :maximum_bid %>
    </div>
    <div class="field">
      <%= label_tag :minimum_bid %><br>
      <%= number_field_tag :minimum_bid %>
    </div>
    <div class="field">
      <%= label_tag :minimum_immediate_price %><br>
      <%= number_field_tag :min_immediate_price %>
    </div>
    <div class="field">
      <%= label_tag :maximum_immediate_price %><br>
      <%= number_field_tag :max_immediate_price %>
    </div>
    <div class="field">
      <%= label_tag :maximum_date_bidding_end %><br>
      <%= date_field_tag :max_date_bidding_end %>
    </div>
    <div class="field">
      <%= label_tag :minimum_date_bidding_end %><br>
      <%= date_field_tag :min_date_bidding_end %>
    </div>
    <div class="field">
      <%= label_tag :maximum_date_bidding_start %><br>
      <%= date_field_tag :max_date_bidding_start %>
    </div>
    <div class="field">
      <%= label_tag :minimum_date_bidding_start %><br>
      <%= date_field_tag :min_date_bidding_start %>
    </div>
    <%= submit_tag 'Go google', class: "btn btn-large btn-primary" %>
    </div>
<% end %>