config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

app/views/shared/_navigation.html.erb
<header>
  <% if logged_in? %>
    <nav class="navbar navbar-default" role="navigation"><%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-large btn-primary" %><%= link_to 'Profile', current_user, class: "btn btn-large btn-primary" %><%= link_to 'Products', products_path, class: "btn btn-large btn-primary" %><%= link_to 'Users', users_path, class: "btn btn-large btn-primary" %><%= link_to 'Evaluations', evaluations_path, class: "btn btn-large btn-primary" %><%= link_to 'Categories', categories_path, class: "btn btn-large btn-primary" %><%= link_to 'Search Page', search_path, class: "btn btn-large btn-primary" %><%= link_to 'Archive', archive_path, class: "btn btn-large btn-primary" %><%= link_to 'Messages', messages_path, class: "btn btn-large btn-primary" %><%= link_to 'Webmaster', webmaster_path, class: "btn btn-large btn-primary" %><%= form_tag common_search_path do %><%= autocomplete_field_tag :title, '', products_path %><%= submit_tag 'Search product', class: "btn btn-large btn-primary" %><% end %></nav>
  <% else %>
    <nav class="navbar navbar-default" role="navigation"><%= link_to 'Login', login_path, class: "btn btn-large btn-primary" %><%= link_to 'Register', new_user_path, class: "btn btn-large btn-primary" %><%= link_to 'Products', products_path, class: "btn btn-large btn-primary" %><%= link_to 'Users', users_path, class: "btn btn-large btn-primary" %><%= link_to 'Evaluations', evaluations_path, class: "btn btn-large btn-primary" %><%= link_to 'Categories', categories_path, class: "btn btn-large btn-primary" %><%= link_to 'Search Page', search_path, class: "btn btn-large btn-primary" %><%= link_to 'Archive', archive_path, class: "btn btn-large btn-primary" %><%= link_to 'Webmaster', webmaster_path, class: "btn btn-large btn-primary" %><%= form_tag common_search_path do %><%= autocomplete_field_tag :title, '', products_path %><%= submit_tag 'Search product', class: "btn btn-large btn-primary" %><% end %></nav>
  <% end %>

  </header>