config/routes.rb
Rails.application.routes.draw do

 
  get 'webmaster/webmaster', to: 'webmaster#webmaster', as: :webmaster

  get 'messages', to: 'messages#index', as: :messages
  get 'messages/:id/new' , to: 'messages#new', as: :message_new
  get 'messages/:id/respond' , to: 'messages#respond', as: :message_respond
  post 'messages/:id/create', to: 'messages#create', as: :message_create
  get 'messages/:id', to: 'messages#show', as: :message
  delete 'messages/:id/', to: 'messages#destroy', as: :message_destroy
  get 'messages/:id/report', to: 'messages#report', as: :message_report

  resources :profiles, only: [:edit, :update]

  post 'search/common_search', to: 'search#common_search', as: :common_search
  get 'search', to: 'search#search', as: :search
  get 'search/google', to: 'search#google', as: :google

  post 'bid/:product_id/mini_bid', to: 'bid#create_minimum_bid', as: :new_minimum_bid
  post 'bid/:product_id/custom_bid', to: 'bid#create_custom_bid', as: :new_custom_bid
  post 'bid/:product_id/max_automatic_bid', to: 'bid#create_max_automatic_bid', as: :new_max_automatic_bid
  post 'bid/:product_id/direct_purchase', to: 'bid#direct_purchase', as: :purchase

  resources :categories
  post 'categories/:category_id/new', to: 'categories#new_child', as: :new_child_category
  post 'categories/:category_id/create', to: 'categories#create_child', as: :create_child_category

  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get '' => 'products#index', as: :root

  get 'evaluations', to: 'evaluations#index'
  post 'evaluations/:evaluationable_type/:evaluationable_id/create', to: 'evaluations#create', as: :create_eval
  get 'evaluations/:evaluationable_type/:evaluationable_id/new', to: 'evaluations#new', as: :new_eval
  get 'evaluations/:id/edit', to: 'evaluations#edit', as: :edit_evaluation
  get 'evaluations/:id', to: 'evaluations#show', as: :evaluation
  patch 'evaluations/:id', to: 'evaluations#update'
  put 'evaluations/:id', to: 'evaluations#update'
  delete 'evaluations/:id', to: 'evaluations#destroy'

  resources :products do
    get :autocomplete_category_name, :on => :collection
  end
  resources :products
  post 'products/:id/confirm', to: 'products#confirm', as: :confirm
  post 'products/:id/not_confirm', to: 'products#not_confirm', as: :not_confirm
  post 'products/:id/:bid_id/pay', to: 'products#pay', as: :pay
  get 'products/:id/more_days', to: 'products#seven_more_days', as: :more_days
  get 'archive', to: 'products#archive', as: :archive
  get 'recommend', to: 'products#recommend', as: :recommend

  resources :users, only: [:index, :new, :create, :show, :destroy]
  post 'users/:id/ban', to: 'users#ban', as: :user_ban
  post 'users/:id/deban', to: 'users#deban', as: :user_deban

  match 'auth/:provider/callback', to: 'sessions_fb#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions_fb#destroy', as: 'signout', via: [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base

  delegate :name, to: :category, prefix: true, allow_nil: true

  belongs_to :user

  belongs_to :category

  has_many :bids, dependent: :destroy

  has_many :evaluations, :as => :evaluationable, dependent: :destroy

  belongs_to :buyer, :class_name => 'User'

  mount_uploader :image, ImageUploader
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader
  mount_uploader :image4, Image4Uploader

  validates :title, length: { in: 3..50 }, uniqueness: { case_sensitive: false }
  validates :description, length: { minimum: 10 }
  validates :immediate_price, numericality: {greater_than: :minimum_price}, allow_blank: true, if: :minimum_price
  validates :minimum_price, numericality: {greater_than_or_equal_to: :start_price}, allow_blank: true
  validates :start_price, numericality: { greater_than_or_equal_to:  0}
  validates :minimum_bid, numericality: {greater_than:  0}
  validates :category_id, presence: true


  # give the value bid in progress for a product
  def bid_in_progress(product)
    all_bid = []
    product.bids.each do |bids|
        all_bid.push(bids.bid)
    end
    all_bid.max
  end

  # give the winner bid in progress for a product
  def bid_winner(product)
    bid = product.bid_in_progress(product)
    winner_bid = Bid.find_by(:product_id => product.id, :bid => bid)
  end

  # give the id bid for the bid in progress
  def bid_id(product)
    bid = Bid.find_by(:bid => product.bid_in_progress(product), :product_id => product.id)
    bid.id
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :confirm, :not_confirm, :seven_more_days, :pay]
  before_action :check_date_bidding_end_all, :check_unsold_product_all, only: :index
  before_action :average_bidding_amount_archive, only: :archive
  before_action :check_date_bidding_end, :check_unsold_product, only: [:show, :edit]
  before_action :editable_or_deletable, only: [:edit, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, :check_status, only: [:edit, :update, :destroy, :seven_more_days]
  before_action :admin, only: [:confirm, :not_confirm]
  autocomplete :category, :name, full: false

  # GET /products
  # GET /products.json
  def index
    @products = Product.order(:title).where("title like ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @products.map{ |tag| {:label => tag.title} }}
    end
  end

  def archive
    @products = Product.where(:status => 'archive')
    respond_to do |format|
      format.html
      format.json { render json: @products.map{ |tag| {:label => tag.title} }}
    end
  end

  def recommend
    ProductMailer.recommend(params[:email], params[:product_id]).deliver_now
    flash[:notice] = 'Email sent to your friend.'
    redirect_to products_path
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if @product.status == 'wait_confirmation' && current_user.admin? == false
      flash[:notice] = 'Product wait confirmation.'
      redirect_to products_path
    end
    views = @product.views+1
    @product.update_attributes(:views => views)
  end

  def confirm
    ProductMailer.confirm(@product).deliver_now
    @product.update(:status => 'In selling', :date_bidding_start => Time.now)
    redirect_to products_path
  end

  def not_confirm
    ProductMailer.not_confirm(@product).deliver_now
    @product.destroy
    redirect_to products_path
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.build_category
  end

  def seven_more_days
    if @product.bids.length != 0
      Bid.destroy_all(:product_id => @product.id)
    end
    @product.update(:date_bidding_end => 7.days.from_now)
    @product.update(:status => 'wait_confirmation')
    ProductMailer.admin_choice(@product).deliver_now
    redirect_to @product
  end

  def pay
    @product.update(:status => 'archive', :buyer_name => (current_user.profile.first_name + '_' + current_user.profile.last_name),
    :buyer_id => current_user.id, :buying_price => @product.bid_in_progress(@product), :buyer_nickname => current_user.profile.nickname)
    Bid.delete_all(:product_id => @product.id)
    redirect_to products_path
  end


  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.date_bidding_end = 7.days.from_now
    @product.date_bidding_start = Time.now
    category = Category.find_by(:name => params[:product][:category_name])
    if category != nil
      @product.category_id = category.id
    end
    @product.user_id = session[:user_id]
    respond_to do |format|
      if @product.save
        ProductMailer.admin_choice(@product).deliver_now
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.status = 'wait_confirmation'
    respond_to do |format|
      if @product.update(product_params)
        ProductMailer.admin_choice(@product).deliver_now
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # check if log in
  def logged_in_user
    unless logged_in?
      flash[:notice] = 'Please log in.'
      redirect_to login_path
    end
  end

  # check date bidding end in show action
  def check_date_bidding_end
    if @product.date_bidding_end < Time.now && @product.status == 'In selling'
      if @product.bids.length == 0 || (@product.minimum_price != nil && @product.minimum_price >
          @product.bid_in_progress(@product))
        @product.update(:status => 'unsold')
        ProductMailer.unsold(@product).deliver_now
      else
        @product.update(:status => 'sold')
        ProductMailer.sold(@product).deliver_now
        ProductMailer.buy(@product).deliver_now
      end
    end
  end

  # destroy unsold product if too old show action
  def check_unsold_product
    if @product.status == 'unsold' && @product.date_bidding_end < 5.days.ago
      @product.destroy
      flash[:notice] = 'This product has been removed.'
      redirect_to products_path
    end
  end

  # destroy unsold product if too old index action
  def check_unsold_product_all
    @products = Product.where(:status => 'unsold')
    @products.each do |product|
      if product.date_bidding_end < 5.days.ago
        product.destroy
      end
    end
  end

  # check status product
  def check_status
    if @product.status == 'unsold' && current_user.admin == false
      flash[:notice] = 'The product has not the good status for that.'
      redirect_to products_path
    end
  end

  # check date bidding end in index action
  def check_date_bidding_end_all
    @products = Product.all
    @products.each do |product|
      if product.date_bidding_end < Time.now && product.status == 'In selling'
        if product.bids.length == 0 || (product.minimum_price != nil && product.minimum_price >
            product.bid_in_progress(product))
          product.update(:status => 'unsold')
          ProductMailer.unsold(product).deliver_now
        else
          product.update(:status => 'sold')
          ProductMailer.sold(product).deliver_now
          ProductMailer.buy(product).deliver_now
        end
      end
    end
  end

  # check if editable and deletable
  def editable_or_deletable
    if (@product.bids.length != 0 || @product.date_bidding_end < Time.now) && current_user.admin == false
      flash[:notice] = 'Product cannot be edit or remove after a first bid or after date bidding end.'
      redirect_to products_path
    end
  end

  # check admin user
  def admin
    unless current_user.admin?
      flash[:notice] = 'You are not admin.'
      redirect_to products_path
    end
  end

  # check authorization user
  def correct_user
    redirect_to(products_path) && flash[:notice] = 'It is not your product.' unless current_owner?(@product)
  end

  # calculate average bid in index
  def average_bidding_amount_archive
    @prods = Product.where(:status => 'archive')
    length = @prods.length
    if length != 0
      average = 0
      @prods.each do |product|
        average += product.buying_price.to_i
      end
      @average = average / length
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:immediate_price, :date_bidding_end, :minimum_price, :start_price, :title,
                                    :description, :user_id, :image, :minimum_bid, :category_id, :status,
                                    :image1, :image2, :image3, :image4)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def current_owner?(product)
    product.user_id == current_user.id || current_user.admin?
  end

end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :immediate_price_optional %><br>
  <%= f.number_field :immediate_price, :step => 0.01 %>
</div>
<div class="field">
  <%= f.label :minimum_price_optional %><br>
  <%= f.number_field :minimum_price, :step => 0.01 %>
</div>
<div class="field">
  <%= f.label :minimum_bid %><br>
  <%= f.number_field :minimum_bid, :step => 0.01 %>
</div>
<div class="field">
  <%= f.label :start_price %><br>
  <%= f.number_field :start_price, :step => 0.01 %>
</div>
<div class="field">
  <%= f.label :title %><br>
  <%= f.autocomplete_field :title, products_path %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description, cols:50, rows:10 %>
</div>
<div class="field">
<p>(max size 300*300) main image</p>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
  <div class="field">
  <p>(max size 300*300)</p>
  <%= f.label :image1 %><br>
  <%= f.file_field :image1 %>
  </div>
 <div class="field">
  <p>(max size 300*300)</p>
  <%= f.label :image2 %><br>
  <%= f.file_field :image2 %>
  </div>
 <div class="field">
  <p>(max size 300*300)</p>
  <%= f.label :image3 %><br>
  <%= f.file_field :image3 %>
  </div>
  <div class="field">
  <p>(max size 300*300)</p>
  <%= f.label :image4 %><br>
  <%= f.file_field :image4 %>
  </div>
<div class="field">
  <%= f.label :category %><br>
  <%= f.autocomplete_field :category_name, autocomplete_category_name_products_path %>
</div>
<% if current_user.admin? %>
<div class="field">
  <%= f.label :date_bidding_end %><br>
  <%= f.date_field :date_bidding_end %>
</div>
<div class="field">
  <%= f.label :date_bidding_start %><br>
  <%= f.date_field :date_bidding_start %>
</div>
<div class="field">
  <%= f.label :status %><br>
  <%= f.text_field :status %>
</div>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table id="products">
  <thead>
  <tr>
    <th>Owner</th>
    <th>Picture</th>
    <th>Immediate price</th>
    <th>Date bidding end</th>
    <th>Date bidding start</th>
    <th>Bidding time left</th>
    <th>Start price</th>
    <th>Minimum bid</th>
    <th>Bid</th>
    <th>Title</th>
    <th>Category</th>
    <th>Description</th>
    <th>Views</th>
    <th>Rate</th>
    <% if logged_in? && current_user.admin? %>
        <th>Status</th>
    <% end %>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <% if product.status == 'In selling' || (logged_in? && current_user.admin?) %>
          <tr>
            <td><% if logged_in? && current_user.admin? %><%= link_to product.user.profile.first_name + ' ' +
                                                          product.user.profile.last_name, user_path(product.user_id) %>
                  <% else %><%= link_to product.user.profile.nickname, user_path(product.user_id) %>
              <% end %></td>
            <td><% if product.image.url != nil %><div class="img"><%= image_tag product.image.url %></div>
              <% else %>empty
              <% end %></td>
            <td><% if product.immediate_price != nil %><%= product.immediate_price %> €
                  <% if logged_in? && product.status == 'In selling' && current_user.id != product.user_id %>
                      <%= button_to 'Purchase', purchase_path(product), method: :post, class: "btn btn-large btn-primary" %>
                  <% end %>
              <% else %>empty<% end %></td>
            <td><%= product.date_bidding_end %></td>
            <td><% if product.status == 'In selling' %><%= product.date_bidding_start %>
              <% else %>Product not confirm<% end %></td>
            <td><% if product.date_bidding_end - Time.now > 0 && product.status == 'In selling' %>
                  <%= distance_of_time_in_words(product.date_bidding_end - Time.now) %>
              <% else %>
                  Bid is over <% if product.status == 'unsold' %><% button_to 'Seven more days', more_days_path(product), class: "btn btn-large btn-primary" %>
                  <% end %>
              <% end %></td>
            <td><%= product.start_price %> €</td>
            <td><%= product.minimum_bid %> €</td>
            <td><% if product.bids.length == 0 %>
                  No bid
              <% else %>
                  <%= product.bid_in_progress(product) %> €
              <% end %>
              <% if logged_in? && Time.now < product.date_bidding_end && product.status == 'In selling' &&
                  product.user_id != current_user.id && (product.bids.length ==0 || product.bid_winner(product).user_id != current_user.id) %>
                  <%= form_tag new_minimum_bid_path(product.id) do %>
                      <%= submit_tag 'Add minimum bid', class: "btn btn-large btn-primary" %>
                  <% end %>
                  <%= form_tag new_custom_bid_path(product.id) do %>
                      <%= number_field_tag :bid, :step => 0.01 %>
                      <%= submit_tag 'Add custom bid', class: "btn btn-large btn-primary" %>
                  <% end %>
                  <%= form_tag new_max_automatic_bid_path(product.id) do %>
                      <%= number_field_tag :bid, :step => 0.01 %>
                      <%= submit_tag 'Add max automatic bid', class: "btn btn-large btn-primary" %>
                  <% end %>
              <% end %>
              <% if logged_in? && product.status == 'sold' && product.bid_winner(product).user_id == current_user.id %>
                  <%= button_to 'Pay ' + product.title, pay_path(product, product.bid_id(product)), method: :post, class: "btn btn-large btn-primary" %>
              <% end %>
              <% if logged_in? && product.bids.length != 0 && product.bid_winner(product).user_id == current_user.id &&
                  product.status =='In selling' %>This is your bid
              <% elsif logged_in? && product.user_id == current_user.id %>This is your product
              <% end %></td>
            <td><%= product.title %></td>
            <td><% if product.category_id != nil%>
                  <%= link_to product.category.name, category_path(product.category.id) %>
              <% else %>
                  empty
              <% end %></td>
            <td><%= product.description %></td>
            <td><%= product.views %></td>
            <td><% if product.evaluations.length != 0 %>
                  <% note = 0 %>
                  <% product.evaluations.each do |evaluation| %>
                      <% note += evaluation.rate %>
                  <% end %>
                  <%= note.round(2) / product.evaluations.length %> / 5
              <% else %>
                  empty
              <% end %></td>
            <% if logged_in? && current_user.admin? %>
                <td><%= product.status %>
                  <% if product.status == 'wait_confirmation' %>
                      <%= button_to 'Confirm', confirm_path(product.id), class: "btn btn-large btn-primary" %><%= button_to 'Not confirm', not_confirm_path(product.id), class: "btn btn-large btn-primary" %>
                  <% end %>
                </td>
            <% end %>
            <td><%= button_to 'Show product', product, method: :get, class: "btn btn-large btn-primary" %>
              <% if logged_in? &&(current_user.id != product.user_id || current_user.admin?) %>
                  <%= link_to 'Add evaluation', new_eval_path('Product', product.id), class: "btn btn-large btn-primary" %>
              <% end %>
              <% if logged_in? && current_user.id != product.user_id %>    
                  <%= button_to 'Ask question' , message_new_path(product.user_id), method: :get, class: "btn btn-large btn-primary" %>
              <% end %>
              <% if logged_in? && ((current_user.id == product.user_id && product.bids.length == 0 &&
                  product.date_bidding_end > Time.now ) || current_user.admin?) %>
                  <%= button_to 'Edit product', edit_product_path(product), method: :get, class: "btn btn-large btn-primary" %>
                  <%= button_to 'Remove product', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %><% end %></td>
          </tr>
      <% end %>
  <% end %>
  <p>Average bidding amount:<strong><% @products = @products.select {|product| product if (product.status == 'In selling')}
                                          average = 0
                                          length = @products.length
                                          if length != 0
                                          @products.each do |product|
                                            average += product.bid_in_progress(product).to_i
                                            end
                                          @average = average / length
                                          end
                                      %><% if @average != nil %><%= @average %><% else %>Empty<% end %></strong></p>
  </tbody>
</table>

<br>

<% if logged_in? %>
    <%= button_to 'New Product', new_product_path, method: :get, class: "btn btn-large btn-primary" %>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? && current_user.admin? %>
    <p>
      <strong>Owner:</strong>
      <%= link_to @product.user.profile.first_name + ' ' + @product.user.profile.last_name, user_path(@product.user_id) %>
    </p>
<% end %>

<p>
  <strong>Owner:</strong>
  <%= link_to @product.user.profile.nickname, user_path(@product.user_id) %>
</p>

<p>
  <strong>Main picture:</strong>
  <% if @product.image.url != nil %>
     <div id="img"><%= image_tag @product.image.url.to_s %></div>
  <% else %>empty
  <% end %>
</p>

<% if @product.image1.url != nil && @product.image2.url != nil && @product.image3.url != nil && @product.image4.url != nil %>
<p>
  <strong>Gallery:</strong>
  <% if @product.image1.url != nil %>
      <div class="img"><%= image_tag @product.image1.url.to_s %></div><br>
  <% end %>
  <% if @product.image2.url != nil %>
      <div class="img"><%= image_tag @product.image2.url.to_s %></div><br>
  <% end %>
  <% if @product.image3.url != nil %>
      <div class="img"><%= image_tag @product.image3.url.to_s %></div><br>
  <% end %>
  <% if @product.image.url != nil %>
      <div class="img"><%= image_tag @product.image3.url.to_s %></div><br>
  <% end %>
</p>
<% end %>

<p>
  <strong>Immediate price:</strong>
  <% if @product.immediate_price != nil %>
      <%= @product.immediate_price %> €
      <% if logged_in? && @product.status == 'In selling' && current_user.id != @product.user_id %>
          <%= button_to 'Purchase', purchase_path(@product), method: :post, class: "btn btn-large btn-primary" %>
      <% end %>
  <% else %>
      empty
  <% end %>
</p>

<p>
  <strong>Date bidding end:</strong>
  <%= @product.date_bidding_end %>
</p>

<p>
  <strong>Date bidding start:</strong>
  <% if @product.status == 'In selling' %>
      <%= @product.date_bidding_start %>
  <% else %>Product not confirm<% end %>
</p>

<p>
  <strong>Bidding time left:</strong>
  <% if @product.date_bidding_end - Time.now > 0 && @product.status == 'In selling' %>
      <%= distance_of_time_in_words(@product.date_bidding_end - Time.now) %>
  <% else %>
      Bid is over <% if @product.status == 'unsold' %><% button_to 'Seven more days', more_days_path(@product), class: "btn btn-large btn-primary" %>
      <% end %>
  <% end %>
</p>

<p>
  <strong>Start price:</strong>
  <%= @product.start_price %> €
</p>

<p>
  <strong>Minimum bid:</strong>
  <%= @product.minimum_bid %> €
</p>

<p>
  <strong>Bid:</strong>
  <% if @product.bids.length == 0 %>
      No bid
  <% else %>
      <%= @product.bid_in_progress(@product) %> €
  <% end %>
  <% if logged_in? && Time.now < @product.date_bidding_end && @product.status == 'In selling' &&
      @product.user_id != current_user.id && (@product.bids.length ==0 || @product.bid_winner(@product).user_id != current_user.id) %>
      <%= form_tag new_minimum_bid_path(@product.id) do %>
          <%= submit_tag 'Add minimum bid', class: "btn btn-large btn-primary" %>
      <% end %>
      <%= form_tag new_custom_bid_path(@product.id) do %>
          <%= number_field_tag :bid, class: 'form-control' %>
          <%= submit_tag 'Add custom bid', class: "btn btn-large btn-primary" %>
      <% end %>
      <%= form_tag new_max_automatic_bid_path(@product.id) do %>
          <%= number_field_tag :bid %>
          <%= submit_tag 'Add max automatic bid', class: "btn btn-large btn-primary" %>
      <% end %>
  <% end %>
  <% if logged_in? && @product.bids.length != 0 && @product.bid_winner(@product).user_id == current_user.id &&
      @product.status == 'In selling' %>This bid is your
  <% elsif logged_in? && @product.user_id == current_user.id %>This is your product
  <% end %>
  <% if logged_in? && @product.status == 'sold' && @product.bid_winner(@product).user_id == current_user.id %>
      <%= button_to 'Pay ' + @product.title, pay_path(@product, @product.bid_id(@product)), method: :post, class: "btn btn-large btn-primary" %>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Views:</strong>
  <%= @product.views %>
</p>

<p>
  <strong>Rate:</strong>
  <% if @product.evaluations.length != 0 %>
      <% note = 0 %>
      <% @product.evaluations.each do |evaluation| %>
          <% note += evaluation.rate %>
      <% end %>
      <%= note.round(2) / @product.evaluations.length %> / 5
  <% else %>
      empty
  <% end %>
</p>

<% if logged_in? && current_user.admin? %>
    <p><strong>Status:</strong>
      <%= @product.status %>
      <% if @product.status == 'wait_confirmation' %>
          <%= button_to 'Confirm', confirm_path(@product.id), class: "btn btn-large btn-primary" %><%= button_to 'Not confirm', not_confirm_path(@product.id), class: "btn btn-large btn-primary" %>
      <% end %>
    </p>
<% end %>

<p>
  <strong>Evaluations:</strong>
  <% if @product.evaluations.length != 0 %>
    <ul>
      <% @product.evaluations.each do |evaluation| %>
          <li><strong>Author:</strong><% if logged_in? && current_user.admin? %><%= link_to evaluation.author_name, user_path(evaluation.user_id) %>
                <% else %><%= link_to evaluation.author_nickname, user_path(evaluation.user_id) %><% end %>
            <strong> Note: </strong><%= evaluation.rate %> / 5 <strong>
            Comment:</strong> <%= evaluation.content %></li>
      <% end %>
    </ul>
<% else %>
    empty
<% end %>
</p>

<%= form_tag recommend_path, method: :get do %>
    <%= hidden_field_tag :product_id, @product.id %>
    <%= email_field_tag :email %>
    <%= submit_tag 'Recommend product', class: "btn btn-large btn-primary" %>
<% end %>

<div id="fb-root"></div>
<div class="fb-share-button" data-layout="button_count" data-mobile-iframe="true"></div>

<% if logged_in? &&(current_user.id != @product.user_id || current_user.admin?) %>
    <%= link_to 'Add evaluation', new_eval_path('Product', @product), class: "btn btn-large btn-primary" %>
<% end %>  
<% if logged_in? && current_user.id != @product.user_id %>  
    <%= link_to 'Ask question' , message_new_path(@product.user_id), class: "btn btn-large btn-primary" %>
<% end %>
<% if logged_in? && ((current_user.id == @product.user_id && @product.bids.length == 0 &&
    @product.date_bidding_end > Time.now) || current_user.admin?) %>
    <%= link_to 'Edit product', edit_product_path(@product), class: "btn btn-large btn-primary" %>
    <%= link_to 'Remove product', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-large btn-primary" %>
<% end %>
<%= link_to 'Back to products list', products_path, class: "btn btn-large btn-primary" %>